#!/usr/bin/python
import dbus
bus = dbus.SessionBus()
try:
    proxy = bus.get_object('org.mpris.MediaPlayer2.spotify','/org/mpris/MediaPlayer2')
    properties_manager = dbus.Interface(proxy, 'org.freedesktop.DBus.Properties')
    # properties_manager.Set('org.mpris.MediaPlayer2.Player', 'Volume', 100.0)
    metadata = properties_manager.Get('org.mpris.MediaPlayer2.Player', 'Metadata')
    playbackStatus = properties_manager.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus')
    if(playbackStatus == "Playing"):
    	print(', '.join(str(x) for x in metadata['xesam:artist']))
except dbus.exceptions.DBusException:
    pass
